name: bahn_plan
description: An app for public transport
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  fluro: ^1.4.0
  flutter:
    sdk: flutter
  flutter_vector_icons: ^0.1.0
  flutter_platform_widgets: ^0.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
